
-- Branch table
CREATE TABLE Branch(

&#x20;   BID INT UNSIGNED NOT NULL,

&#x20;   BNAME VARCHAR(20) NOT NULL,

&#x20;   ADDRESS VARCHAR(20) NOT NULL,

&#x20;   PINCODE INT UNSIGNED NOT NULL,

&#x20;   CONSTRAINT P_BID PRIMARY KEY(BID),

&#x20;   CONSTRAINT U_PIN UNIQUE(PINCODE),

&#x20;   CONSTRAINT C_PIN CHECK(LENGTH(PINCODE)=6));