-- Customer table

CREATE TABLE CUSTOMER(

CID INT UNSIGNED NOT NULL PRIMARY KEY AUTO\_INCREMENT,

CNAME VARCHAR(30) NOT NULL,

ADDRESS VARCHAR(100) NOT NULL,

PHONE BIGINT UNSIGNED NOT NULL UNIQUE CHECK(LENGTH(PHONE)=10),

EMAIL VARCHAR(40) NULL,

BALANCE DECIMAL(5,3) UNSIGNED NOT NULL DEFAULT "10",

GENDER ENUM("MALE","FEMALE") NOT NULL,

SID INT UNSIGNED NULL,

CONSTRAINT FOREIGN KEY(SID) REFERENCES STUDENT(SID)

);